<?php

namespace App\Models\Backend;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Advertisement extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'title',
        'content',
        'banner',
        'redirect_url',
        'slug',
        'status',
    ];

    protected $searchableFields = ['*'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($advertisement) {
            if (file_exists($advertisement->banner)) {
                unlink($advertisement->banner);
            }
        });
    }

    public static function createOrUpdateAdvertisement($request, $advertisement = null)
    {
        if ($advertisement === null) {
            $advertisement = new self();
        }

        $advertisement->title = $request->input('title');
        $advertisement->content = $request->input('content');
        $advertisement->banner = imageUpload($request->file('banner'), 'advertisements', 'advertisements', 600, 500, $advertisement->banner ?? null);
        $advertisement->redirect_url = $request->input('redirect_url');
        $advertisement->slug = str_replace(' ', '-', $request->title);
        $advertisement->status = $request->status == 'on' ? 1 : 0;

        return $advertisement->save() ? $advertisement : null;
    }
}
