<?php

namespace App\Models\Backend;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class EmployeeDocument extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'user_id',
        'title',
        'file',
        'file_thumb',
        'file_type',
        'file_size',
        'status',
        'slug',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($employeeDocument) {
            if (file_exists($employeeDocument->file)) unlink($employeeDocument->file);
            if (file_exists($employeeDocument->file_thumb)) unlink($employeeDocument->file_thumb);
        });
    }

    protected $searchableFields = ['*'];

    protected $table = 'employee_documents';

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
