<?php

namespace App\Models\Backend;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class FieldOfStudy extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['field_name', 'note', 'status', 'slug'];

    protected $searchableFields = ['*'];

    protected $table = 'field_of_studies';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($fieldOfStudy) {
            // Delete all education subject names associated with this field of study
            $fieldOfStudy->educationSubjectNames()->delete();
//            $fieldOfStudy->employeeEducations()->delete();
//            $fieldOfStudy->jobTasks()->delete();
        });
    }

    public static function createOrUpdateFieldOfStudies($request, $fieldOfStudy = null)
    {
        if (!$fieldOfStudy) {
            $fieldOfStudy = new self();
        }
        $fieldOfStudy->field_name = $request->field_name;
        $fieldOfStudy->note = $request->note;
        $fieldOfStudy->status = $request->status == 'on' ? 1 : 0;
        $fieldOfStudy->slug = str_replace(' ', '-', $request->field_name);
        $fieldOfStudy->save();
        return $fieldOfStudy;
    }

    public function educationSubjectNames()
    {
        return $this->hasMany(EducationSubjectName::class);
    }

    public function employeeEducations()
    {
        return $this->hasMany(EmployeeEducation::class);
    }

    public function jobTasks()
    {
        return $this->belongsToMany(JobTask::class);
    }
}
