<?php

namespace App\Models\Backend;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class SkillsCategory extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['category_name', 'note', 'slug', 'status'];

    protected $searchableFields = ['*'];

    protected $table = 'skills_categories';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($skillCategory) {
            // Delete all skills associated with this category
            $skillCategory->skills()->delete();
        });
    }

    public static function createOrUpdateSkillsCategory($request, $skillCategory = null)
    {
        if (!$skillCategory) {
            $skillCategory = new self();
        }
        $skillCategory->category_name = $request->category_name;
        $skillCategory->note = $request->note;
        $skillCategory->status = $request->status == 'on' ? 1 : 0;
        $skillCategory->slug = str_replace(' ', '-', $request->category_name);
        $skillCategory->save();
        return $skillCategory;
    }

    public function skills()
    {
        return $this->hasMany(Skill::class);
    }
    public function publishedSkills()
    {
        return $this->hasMany(Skill::class)->where('status', 1);
    }
}
